# Generated by Django 5.2.11 on 2026-02-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('document_type', models.CharField(choices=[('memorandum', 'Memorandum'), ('letter', 'Letter'), ('report', 'Report'), ('form', 'Form'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('template_content', models.TextField(help_text='HTML template content')),
                ('css_content', models.TextField(blank=True, help_text='CSS styling')),
                ('js_content', models.TextField(blank=True, help_text='JavaScript for interactivity')),
                ('agent_role', models.CharField(blank=True, choices=[('orchestrator', 'Orchestrator'), ('analyst', 'Analyst'), ('pm', 'Project Manager'), ('architect', 'Architect'), ('scrum_master', 'Scrum Master'), ('developer', 'Developer'), ('qa', 'QA Engineer')], max_length=50)),
                ('agent_roles', models.JSONField(blank=True, default=list)),
                ('workflow_phase', models.CharField(blank=True, choices=[('planning', 'Planning'), ('development', 'Development')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('template_type', models.CharField(choices=[('template', 'Document Template'), ('agent', 'Agent Prompt')], default='template', max_length=20)),
                ('source_file', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('template_variables', models.TextField(blank=True, help_text='JSON object defining required variables')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('content', models.TextField(help_text='Generated HTML content')),
                ('variables_used', models.TextField(blank=True, help_text='JSON object with variables used in generation')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.IntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_created', to=settings.AUTH_USER_MODEL)),
                ('parent_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='forge.generateddocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_documents', to='forge.documenttemplate')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('downloaded', 'Downloaded'), ('deleted', 'Deleted')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.TextField(blank=True, help_text='JSON object with additional activity context')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='forge.generateddocument')),
            ],
            options={
                'verbose_name': 'Document Activity',
                'verbose_name_plural': 'Document Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='documenttemplate',
            index=models.Index(fields=['agent_role', 'workflow_phase'], name='forge_docum_agent_r_f568bc_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['status', 'created_at'], name='forge_gener_status_2e79c9_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['template', 'status'], name='forge_gener_templat_05b18d_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['document', 'timestamp'], name='forge_docum_documen_d13c73_idx'),
        ),
        migrations.AddIndex(
            model_name='documentactivity',
            index=models.Index(fields=['user', 'timestamp'], name='forge_docum_user_id_6cb6fe_idx'),
        ),
    ]
